### ISSUE TITLE
Render glitches (blacked out content)

### ISSUE THREAD

**Issue by willmcgugan** [xtermjs/xterm.js#4480]
I'm working on a TUI framework for Python, which does tend to push the terminal more than a typical app.

On certain apps, after a few seconds of updates the terminal starts glitching heavily. The more animation, the quicker this seems to happen.

It's probably best to show in a video:

https://user-images.githubusercontent.com/554369/232790539-52d3907d-ccb4-48dc-941a-766ad80d04c8.mov

This doesn't occur on other terminals. And I'm fairly sure (although not 100%) that this is not an error in Textual itself.

The video above is with an embedded xterm.js, but this issue also occurs in VSCode.

I haven't addressed flow control yet. But from experimentation, it only takes a a few hundred K before this issue occurs.

## Details
- Browser and browser version:  Chrome. Version 112.0.5615.49 (Official Build) (arm64)
- OS version:  MacOS 13.3.1 (22E261)
- xterm.js version: 5.1.0"

### Steps to reproduce

Install Textual:

```
pip install textual[dev]
```

Then in VS code integrated terminal:

```
textual easing
```

**Comment by willmcgugan** [comment]
Possibly part of the same issue, but if I keep clicking the app in this glitched state, then a different glitch occurs.

https://user-images.githubusercontent.com/554369/232797957-7a859d35-5c39-4972-a73b-3f4d22b62714.mp4

Which looks like some kind of texture cache has become corrupt?

**Comment by jerch** [comment]
To me both looks like texture cache issues, but at different levels - 1. looks like no invalidate/erase going on, as if nothing gets into textures anymore (works fine in the beginning). 2. looks like a cache key collision, placing stuff into wrong place. (Quickly tested in xterm.js demo under linux/chrome and firefox...)

One question regarding your screen updates - from terminal logs it seems that you do a full screen updates for every animation step. Wouldn't a diff buffer approach save a lot of bandwidth and TE work here?

**Comment by willmcgugan** [comment]
After some investigation, I've found that it is nothing to do with the speed or volume of updates. It seems to be triggered when Textual writes a large number of different colors.

If I disable the blending effect in the video above, then I can't reproduce the issue at all.

I can reproduce this outside of Textual. I've documented this in https://github.com/xtermjs/xterm.js/issues/4484

**Comment by willmcgugan** [comment]
I've found that calling `clearTextureAtlas` after every write essentially fixes this issue. I'm assuming this is sub-optimal, and it does seem a little slower to update.

**Comment by jerch** [comment]
> I've found that calling `clearTextureAtlas` after every write essentially fixes this issue. I'm assuming this is sub-optimal, and it does seem a little slower to update.

This kinda confirms that there is an issue with eviction in the cache, like it is ever-growing until an upper bound is hit (thats also what I see in the demo, the atlas pages grow really big there from your easing example).
Since I have not dealt with the atlas implementation myself this prolly has to wait until @Tyriar finds some time to look into it.

**Comment by Tyriar** [comment]
>  I'm assuming this is sub-optimal, and it does seem a little slower to update.

Very, especially if you use a lot of unique glyphs. You don't seem to use that much other than the fading of the yellow square.

https://github.com/xtermjs/xterm.js/issues/4351 is the only issue I was aware of with the texture atlas currently, it's possibly the same.

@willmcgugan what renderer is that using?

**Comment by Tyriar** [comment]
Maybe related? https://github.com/xtermjs/xterm.js/issues/4485

**Comment by jerch** [comment]
@Tyriar It still repros with #4527, which fixes #4485.

**Comment by jerch** [comment]
@Tyriar Did a bit more digging.

For webgl the issue gets resolved by this change:
```diff
diff --git a/addons/xterm-addon-webgl/src/WebglRenderer.ts b/addons/xterm-addon-webgl/src/WebglRenderer.ts
index fcb0dd80..2b96c7d6 100644
--- a/addons/xterm-addon-webgl/src/WebglRenderer.ts
+++ b/addons/xterm-addon-webgl/src/WebglRenderer.ts
@@ -338,10 +338,13 @@ export class WebglRenderer extends Disposable implements IRenderer {
     // Tell renderer the frame is beginning
     if (this._glyphRenderer.beginFrame()) {
       this._clearModel(true);
+      this._updateModel(0, this._terminal.rows);
+    } else {
+      this._updateModel(start, end);
     }
 
     // Update model to reflect what's drawn
-    this._updateModel(start, end);
+    //this._updateModel(start, end);
 
     // Render
     this._rectangleRenderer?.render();
```
which forces the model into a full refresh upon a page merge in the atlas.

For canvas the issue goes away, if comment out the bitmap usage here:
```diff
diff --git a/addons/xterm-addon-canvas/src/BaseRenderLayer.ts b/addons/xterm-addon-canvas/src/BaseRenderLayer.ts
index 88d929f1..06185528 100644
--- a/addons/xterm-addon-canvas/src/BaseRenderLayer.ts
+++ b/addons/xterm-addon-canvas/src/BaseRenderLayer.ts
@@ -388,7 +388,8 @@ export abstract class BaseRenderLayer extends Disposable implements IRenderLayer
       this._bitmapGenerator[glyph.texturePage]!.version = this._charAtlas.pages[glyph.texturePage].version;
     }
     this._ctx.drawImage(
-      this._bitmapGenerator[glyph.texturePage]?.bitmap || this._charAtlas!.pages[glyph.texturePage].canvas,
+      // this._bitmapGenerator[glyph.texturePage]?.bitmap || this._charAtlas!.pages[glyph.texturePage].canvas,
+      this._charAtlas!.pages[glyph.texturePage].canvas,
       glyph.texturePosition.x,
       glyph.texturePosition.y,
       glyph.size.x,
```
It looks like some issue with the bitmap used after a page merge. Also `bitmap.close()` is never called in the bitmap lifecycling (not sure if JS will fully cleanup bitmaps by GC, still wondering why there is an explicit `ImageBitmap.close`).

Since I am not sure, if these are the right fixes (not familiar with the renderer code), I'd leave it up to you.

**Comment by Tyriar** [comment]
@jerch the first one is definitely the first fix as when `beginFrame` returns true the atlas is cleared/merged so any pointers they have to textures become invalidated:

https://github.com/Tyriar/xterm.js/blob/eb56356133c91df39fbdab2e416d30a79d678acd/src/browser/renderer/shared/TextureAtlas.ts#L192-L194

You can PR that fix if you want, I'll look into the second one now as we don't want to lose the bitmap optimization

**Comment by jerch** [comment]
Ah ok, gonna do the webgl PR then.

**Comment by jerch** [comment]
@Tyriar Still not fully fixed - seeing the glitch as showed here https://github.com/xtermjs/xterm.js/issues/4480#issuecomment-1513196157

To me this also looks like a different issue :point_right: #4534

**Comment by willmcgugan** [comment]
I can still reproduce this isssue. Tried with the latest xterm and xterm-addon-webgl, and the beta versions.

Seems the same in VSCode:

<img width="2083" alt="Screenshot 2023-07-15 at 17 48 55" src="https://github.com/xtermjs/xterm.js/assets/554369/fe0a6cb0-a364-4685-a673-2584188188b8">
